runtime: nodejs16

env_variables:
  # Server
  PORT: '3000'
  API_URL: 'http://localhost:3000'
  JWT_SECRET: 'Pyitq7vry43VQyVn6epYyoPYJ1FHIIH8hlwvuNxZHMSldAxI1ffbBan4izp2coY'

  # Database
  DB_NAME: 'collabolio'
  MONGO_DB: 'mongodb+srv://aszaychik:njpQKZaIUYUQZadB@collabolio.pz75dki.mongodb.net/?retryWrites=true&w=majority'

  # SMTP
  SMTP_USER: 'aszaychik@gmail.com'
  SMTP_PASS: 'jylfuvokatbdubdg'

handlers:
  - url: /.*
    script: npm run serve
